[package]
name = "dht"
version = "0.1.0"
authors = ["gurv-s <vargwin@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
hex = "0.3.2"
log = "0.4.6"
runtime = "0.3.0-alpha.4"
futures-preview = "0.3.0-alpha.16"