[package]
name = "dht"
version = "0.1.0"
authors = ["gurv-s <vargwin@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
num-bigint = { version = "0.2", features = ["rand"] }
hex = "0.3"
log = "0.4"
byteorder = "1.3"
