[package]
name = "dht"
version = "0.1.0"
authors = ["95th <vargwin@gmail.com>"]
edition = "2018"

[dependencies]
bencode = { path = "../bencode" }
common = { path = "../common" }
bitflags = "1.1"
ed25519-dalek = "0.9.1"
sha2 = "0.8.0"
defaults = "0.2.0"
