strategy:
  matrix:
    Linux:
      vmImage: ubuntu-latest
      rustup_toolchain: nightly
    MacOS:
      vmImage: macOS-latest
      rustup_toolchain: nightly
    Windows:
      vmImage: windows-latest
      rustup_toolchain: nightly

pool:
  vmImage: $(vmImage)

steps:
  - bash: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: cargo build --all
    displayName: Cargo build
  - script: cargo test --all
    displayName: Cargo test
  