[package]
name = "torrent-rs"
version = "0.1.0"
authors = ["gurv-s <vargwin@gmail.com>"]
edition = "2018"

[dependencies]
bencode = { path = "bencode" }
ed25519-dalek = "0.9.1"
rand = "0.6.5"
digest = "0.8.0"

[profile.release]
lto = "yes"