[package]
name = "torrent-rs"
version = "0.1.0"
authors = ["95th <vargwin@gmail.com>"]
edition = "2018"

[workspace]
members = ["bencode", "dht"]

[dependencies]
bencode = { path = "bencode" }
dht = { path = "dht" }