[package]
name = "torrent-rs"
version = "0.1.0"
authors = ["95th <vargwin@gmail.com>"]
edition = "2018"

[workspace]
members = ["bencode", "dht", "common"]

[dependencies]
bencode = { path = "bencode" }
dht = { path = "dht" }
common = { path = "common" }
bitflags = "1.1"
defaults = "0.1.0"
